# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         g-cpan
version:      0.15.0
version_from: bin/g-cpan
installdirs:  site
requires:
    File::Basename:                0
    File::Copy:                    0
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0
    IO::File:                      0
    Log::Agent:                    0
    Memoize:                       0
    Shell::EnvImporter:            0
    Term::ANSIColor:               0
    Test::More:                    0
    YAML:                          0
    YAML::Node:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
